[package]
name = "classify"
version = "0.1.0"
authors = ["WasmEdge"]
edition = "2021"

[lib]
name = "classify"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.61"
wasmedge_tensorflow_interface = "^0.2.0"
wasmedge-bindgen = "0.4.0"
wasmedge-bindgen-macro = "0.4.0"